export const Users = [
  {
    id: 1,
    profilePicture: "assets/profilepersion/pic-p-1.jpg",
    userName: "safak Kagolaei",
  },
  {
    id: 2,
    profilePicture: "assets/profilepersion/pic-p-2.jpg",
    userName: "sirvan Khosravi",
  },
  {
    id: 3,
    profilePicture: "assets/profilepersion/pic-p-3.jpg",
    userName: " ali Daei",
  },
  {
    id: 4,
    profilePicture: "assets/profilepersion/pic-p-4.jpg",
    userName: "anil neimar",
  },
  {
    id: 5,
    profilePicture: "assets/profilepersion/pic-p-5.jpg",
    userName: "antoni quin",
  },
  {
    id: 6,
    profilePicture: "assets/profilepersion/pic-p-6.jpg",
    userName: "berad pit",
  },
  {
    id: 7,
    profilePicture: "assets/profilepersion/pic-p-7.jpg",
    userName: "jorj keloni",
  },
  {
    id: 8,
    profilePicture: "assets/profilepersion/pic-p-8.jpg",
    userName: "david behkam",
  },
  {
    id: 9,
    profilePicture: "assets/profilepersion/pic-p-9.jpg",
    userName: "kelian embape",
  },
  {
    id: 10,
    profilePicture: "assets/profilepersion/pic-p-10.jpg",
    userName: "Cristiano ronaldo",
  },
];

export const Posts = [
  {
    id: 1,
    desk: "Love For All ,Hatred for none",
    photo: "assets/post/post -1.jpg",
    data: "15 min ago",
    userId: 1,
    like: 2,
    comment: 1,

  },
  {
    id: 2,
    desk: "Love For All ,Hatred for none",
    photo: "assets/post/post -2.jpg",
    data: "25 min ago",
    userId: 2,
    like: 5,
    comment: 12,
  },
  {
    id: 3,
    desk: "Love For All ,Hatred for none",
    photo: "assets/post/post -3.jpg",
    data: "14 min ago",
    userId: 3,
    like: 18,
    comment: 19,
  },
  {
    id: 4,
    desk: "Love For All ,Hatred for none",
    photo: "assets/post/post-4.jpg",
    data: "2 min ago",
    userId: 4,
    like: 23,
    comment: 16,
  },
  {
    id: 5,
    desk: "Love For All ,Hatred for none",
    photo: "assets/post/post-5.jpg",
    data: "7 min ago",
    userId: 5,
    like: 74,
    comment: 9,
  },
  {
    id: 6,
    desk: "Love For All ,Hatred for none",
    photo: "assets/post/post-6.jpg",
    data: "25 min ago",
    userId: 6,
    like: 16,
    comment: 33,
  },
  {
    id: 7,
    desk: "Love For All ,Hatred for none",
    photo: "assets/post/post-7.jpg",
    data: "17 min ago",
    userId: 7,
    like: 9,
    comment: 2,
  },
  {
    id: 8,
    desk: "Love For All ,Hatred for none",
    photo: "assets/post/post-8.jpg",
    data: "3  min ago",
    userId: 8,
    like: 8,
    comment: 11,
  },
  {
    id: 9,
    desk: "Love For All ,Hatred for none",
    photo: "assets/post/post-9.jpg",
    data: "45 min ago",
    userId: 9,
    like: 60,
    comment: 30,
  },
  {
    id: 10,
    desk: "Love For All ,Hatred for none",
    photo: "assets/post/post-10.jpg",
    data: "1 min ago",
    userId: 10,
    like: 35,
    comment: 7,
  },
  
];
